{
    'name': 'AFR ECM — Enterprise Content Management',
    'version': '16.0.1.1.1',
    'category': 'Document Management',
    'summary': 'ECM sobre OCA dms: tipos de documento, metadados, confidencialidade, audit log e acervo físico com QR',
    'author': 'Engenapp',
    'license': 'LGPL-3',
    'depends': [
        'base',
        'mail',
        'web',
        'dms',
        'dms_user_role',
        'hr_dms_field',
    ],
    'data': [
        'security/security.xml',
        'security/ir.model.access.csv',
        'security/record_rules.xml',
        'data/document_type_data.xml',
        'data/mail_activity_data.xml',
        'reports/location_label_template.xml',
        'reports/location_label_report.xml',
        'views/document_type_views.xml',
        'views/physical_location_views.xml',
        'views/audit_log_views.xml',
        'views/dms_file_views.xml',
        'views/dms_directory_views.xml',
        'views/menus.xml',
    ],
    'external_dependencies': {
        'python': ['qrcode'],
    },
    'installable': True,
    'application': True,
}
