{
    'name': 'IoT WireGuard Enrollment',
    'icon': '/afr_iot_wireguard/static/description/icon.png',
    'version': '16.0.1.0.0',
    'category': 'Technical',
    'summary': 'Gestão de dispositivos IoT via WireGuard com enrollment por QR code',
    'author': 'Engenapp',
    'depends': ['base', 'mail'],
    'data': [
        'security/wireguard_security.xml',
        'security/ir.model.access.csv',
        'data/wg_manager_config.xml',
        'data/ir_cron.xml',
        'views/res_config_settings_views.xml',
        'views/wireguard_device_views.xml',
        'views/wireguard_enrollment_views.xml',
        'views/activate_template.xml',
        'views/menus.xml',
    ],
    'installable': True,
    'application': True,
    'license': 'LGPL-3',
}
